
variables:
  MYSQL_DATABASE: 'bookStore'
  MYSQL_ROOT_PASSWORD: 'admin'

stages:
  - build
  - checkstyle
  - test_coverage_check
  - db
  - deploy_job
  - tests
  - e2e_test


#############################################################JOBS#######################################################

build_job:
  stage: build
  image: maven:3.8.3-openjdk-17
  script:
    - echo "Building the application..."
    - mvn clean package -DskipTests # Example for a Maven Java project
  artifacts:
    paths:
      - target/*.jar

checkstyle:
  stage: checkstyle
  image: maven:3.8.3-openjdk-17
  script:
    - mvn checkstyle:check
  dependencies:
    - build_job
  only:
    - ci

test_coverage_check:
  stage: test_coverage_check
  image: maven:3.8.3-openjdk-17
  script:
    - echo "Checking test coverage..."
    - mvn jacoco:report
  dependencies:
    - build_job
  only:
    - ci

db:
  stage: db
  image: ubuntu:20.04
  services:
    - name: mysql:5.7
      alias: mysql
  variables:
      MYSQL_DATABASE: 'bookStore'
      MYSQL_ROOT_PASSWORD: 'admin'
  before_script:
    - apt-get update && apt-get install -y default-mysql-client wget openjdk-17-jdk-headless
    - wget -O maven.tar.gz "https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz"
    - tar -xvzf maven.tar.gz -C /opt
    - ln -s /opt/apache-maven-3.9.9/bin/mvn /usr/bin/mvn
    - mvn --version
    - mysql --version
    - sleep 30
    - echo "Checking MySQL service connectivity..."
    - echo "CREATE DATABASE IF NOT EXISTS bookStore; USE bookStore; CREATE TABLE IF NOT EXISTS books (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL);" | mysql -u root -p"${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"
  script:
      - mvn clean install -DskipTests
      - mvn spring-boot:run -Dspring-boot.run.arguments="--spring.datasource.url=jdbc:mysql://mysql:3306/bookStore?useSSL=false&serverTimezone=UTC --spring.datasource.username=root --spring.datasource.password=admin" &
      - sleep 30  # Give time for the application to start

deploy_job:
  stage: deploy_job
  script:
    - echo "Deploying the application..."
    - java -jar target/bookStore-0.0.1-SNAPSHOT.jar & # Example for running a Java application
  artifacts:
    paths:
      - target/*.jar
  dependencies:
    - build_job

unit_tests:
  stage: tests
  image: ubuntu:20.04
  services:
    - name: mysql:8.0
      alias: mysql
  variables:
    MYSQL_DATABASE: 'bookStore'
    MYSQL_ROOT_PASSWORD: 'admin'
  before_script:
    - apt-get update && apt-get install -y default-mysql-client wget openjdk-17-jdk-headless
    - wget -O maven.tar.gz "https://downloads.apache.org/maven/maven-3/3.9.9/binaries/apache-maven-3.9.9-bin.tar.gz"
    - tar -xvzf maven.tar.gz -C /opt
    - ln -s /opt/apache-maven-3.9.9/bin/mvn /usr/bin/mvn
    - mvn --version
    - mysql --version
    - sleep 20
    - echo "Database host is '${MYSQL_HOST}'"
    - echo "Database password is '${MYSQL_ROOT_PASSWORD}'"
    - while ! mysqladmin ping -u root -p"$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE" --silent; do
        echo "Waiting for MySQL...";
        sleep 1;
      done
    #- echo "SHOW tables;"| mysql -u root -p"$MYSQL_ROOT_PASSWORD" -h mysql "$MYSQL_DATABASE"
    - echo "Checking MySQL service connectivity..."
    - echo "CREATE DATABASE IF NOT EXISTS bookStore; USE bookStore; CREATE TABLE IF NOT EXISTS books (id INT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL);" | mysql -u root -p"${MYSQL_ROOT_PASSWORD}" --host=mysql "${MYSQL_DATABASE}"
    - echo "Deploying the application..."
    - sleep 30
    - java -jar target/bookStore-0.0.1-SNAPSHOT.jar & # Example for running a Java application
  script:
    - echo "Running unit tests..."
    - mvn clean -Dtest=com.bookStore.tests.*Tests test
  artifacts:
    paths:
      - target/*.jar
  dependencies:
    - build_job
  only:
    - ci

e2e_test:
  stage: e2e_test
  services:
    - selenium/standalone-chrome
  script:
    - echo "Building the project..."
    - mvn clean -Dtest=ui.*Tests Dheadless=true test
  only:
    - ci
